export enum TTSErrorCode {
  BINARY_NOT_FOUND = 'BINARY_NOT_FOUND',
  BINARY_DOWNLOAD_FAILED = 'BINARY_DOWNLOAD_FAILED',
  BINARY_PERMISSION_DENIED = 'BINARY_PERMISSION_DENIED',
  BINARY_GATEKEEPER_BLOCKED = 'BINARY_GATEKEEPER_BLOCKED',
  BINARY_CORRUPT = 'BINARY_CORRUPT',
  MODEL_NOT_FOUND = 'MODEL_NOT_FOUND',
  MODEL_DOWNLOAD_FAILED = 'MODEL_DOWNLOAD_FAILED',
  MODEL_CORRUPT = 'MODEL_CORRUPT',
  SYNTHESIS_FAILED = 'SYNTHESIS_FAILED',
  SYNTHESIS_TIMEOUT = 'SYNTHESIS_TIMEOUT',
  EMPTY_TEXT = 'EMPTY_TEXT',
  TEXT_TOO_LONG = 'TEXT_TOO_LONG',
  UNSUPPORTED_PLATFORM = 'UNSUPPORTED_PLATFORM',
  NETWORK_ERROR = 'NETWORK_ERROR',
}

export class TTSError extends Error {
  constructor(
    public readonly code: TTSErrorCode,
    message: string,
    public readonly cause?: Error,
  ) {
    super(message);
    this.name = 'TTSError';
  }
}
