export enum TTSErrorCode {
  BINARY_NOT_FOUND = 'BINARY_NOT_FOUND',
  BINARY_DOWNLOAD_FAILED = 'BINARY_DOWNLOAD_FAILED',
  BINARY_PERMISSION_DENIED = 'BINARY_PERMISSION_DENIED',
  BINARY_GATEKEEPER_BLOCKED = 'BINARY_GATEKEEPER_BLOCKED',
  BINARY_CORRUPT = 'BINARY_CORRUPT',
  MODEL_NOT_FOUND = 'MODEL_NOT_FOUND',
  MODEL_DOWNLOAD_FAILED = 'MODEL_DOWNLOAD_FAILED',
  MODEL_CORRUPT = 'MODEL_CORRUPT',
  SYNTHESIS_FAILED = 'SYNTHESIS_FAILED',
  SYNTHESIS_TIMEOUT = 'SYNTHESIS_TIMEOUT',
  EMPTY_TEXT = 'EMPTY_TEXT',
  TEXT_TOO_LONG = 'TEXT_TOO_LONG',
  UNSUPPORTED_PLATFORM = 'UNSUPPORTED_PLATFORM',
  NETWORK_ERROR = 'NETWORK_ERROR',
  // CLI-specific errors
  NO_INPUT = 'NO_INPUT',
  INVALID_INPUT = 'INVALID_INPUT',
  FILE_NOT_FOUND = 'FILE_NOT_FOUND',
  FILE_READ_ERROR = 'FILE_READ_ERROR',
  STDIN_TIMEOUT = 'STDIN_TIMEOUT',
  STDIN_READ_ERROR = 'STDIN_READ_ERROR',
  INPUT_TOO_LARGE = 'INPUT_TOO_LARGE',
  NO_AUDIO_PLAYER = 'NO_AUDIO_PLAYER',
  PLAYBACK_ERROR = 'PLAYBACK_ERROR',
  TEMP_FILE_ERROR = 'TEMP_FILE_ERROR',
  CONFIG_READ_ERROR = 'CONFIG_READ_ERROR',
  CONFIG_WRITE_ERROR = 'CONFIG_WRITE_ERROR',
  CONFIG_RESET_ERROR = 'CONFIG_RESET_ERROR',
  INVALID_CONFIG = 'INVALID_CONFIG',
  INVALID_CONFIG_KEY = 'INVALID_CONFIG_KEY',
  INVALID_CONFIG_VALUE = 'INVALID_CONFIG_VALUE',
}

export class TTSError extends Error {
  constructor(
    public readonly code: TTSErrorCode,
    message: string,
    public readonly cause?: Error,
  ) {
    super(message);
    this.name = 'TTSError';
  }
}
